### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by probonopd** [bildschirmtext/btx_decoder#1]
Do you think we can make it compile on macOS 10.10? Geting

```
/Users/travis/build/probonopd/btx_decoder/layer6.c:1082:24: warning: incompatible pointer types passing 'char [4][24]' to parameter of type 'char *' [-Wincompatible-pointer-types]
            define_raw_DRC(c, data, t.drcs_bits);
                              ^~~~
In file included from /Users/travis/build/probonopd/btx_decoder/layer6.c:44:
/Users/travis/build/probonopd/btx_decoder/xfont.h:9:41: note: passing argument to parameter 'data' here
extern void define_raw_DRC(int c, char *data, int bits);
                                        ^
/Users/travis/build/probonopd/btx_decoder/layer6.c:1697:13: error: redeclaration of 'scroll' must have the 'overloadable' attribute
static void scroll(int up)
            ^
/Users/travis/build/probonopd/btx_decoder/layer6.c:102:13: note: previous overload of function is here
static void scroll(int up);
            ^
1 warning and 1 error generated.
```

- https://travis-ci.com/probonopd/btx_decoder/builds/98373534#L219-L232
- https://github.com/probonopd/btx_decoder/blob/9377b4e604f5a93be37acf002b08a1687745976d/.travis.yml

**Comment by mist64** [comment]
I can't see where the conflicting declaration of "scroll()" would come from. Can you try renaming it to scroll_() temporarily and see whether that fixes it?

**Comment by probonopd** [comment]
Did not really help...

**Comment by mist64** [comment]
Same error?

**Comment by probonopd** [comment]
Looks like using Xcode 6.4 causes this issue. I am trying to build this in a way that it runs on systems as old as OS X 10.9 if possible. (Apple refuses older hardware the latest OS releases.)

**Comment by probonopd** [comment]
Looks like you know a lot about Macs 👍 I will experiment a bit more.
